apiVersion: v1
kind: Service
metadata:
  name: nginx-devops
  namespace: devops-portfolio
spec:
  type: NodePort
  selector:
    app: nginx-devops
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30001
