apiVersion: v1
kind: Service
metadata:
  name: nginx-devops-fallback
  namespace: devops-portfolio
spec:
  type: ClusterIP
  selector:
    app: nginx-devops
  ports:
  - name: http
    port: 9090
    targetPort: 80
